Shippable/base

- data/state.json
- scripts/installCore.sh
- scripts/remote/installGitlab.sh
- scripts/remote/installVault.sh
https://github.com/Shippable/base/issues/6
https://github.com/Shippable/base/issues/7
also fixing ParseError in state.json file
> Installing vault in core DB machine & gitlab in core swarm machine

- scripts/installCore.sh
- scripts/remote/installRabbit.sh
https://github.com/Shippable/base/issues/5
> Add base rabbitmq script

- base.sh
Closes https://github.com/Shippable/base/issues/4
> Fix handling of dependencies

- base.sh
- data/redis.conf
- scripts/_copyRemote.sh
- scripts/installCore.sh
- scripts/remote/installRedis.sh
https://github.com/Shippable/base/issues/10
> Installing redis on core Swarm machine

- scripts/remote/installDocker.sh
fixes https://github.com/Shippable/base/issues/21
> install docker latest version

- data/pgpass.conf
- scripts/installCore.sh
- scripts/remote/bootstrapVault.sh
- scripts/remote/installVault.sh
- scripts/remote/pgpass.conf
- scripts/remote/vault.sql
https://github.com/Shippable/base/issues/23
> bootstrapping vault

- scripts/installCore.sh
- scripts/remote/installVault.sh
https://github.com/Shippable/base/issues/6
> starting vault right after installation

- scripts/installCore.sh
- scripts/remote/installVault.sh
> Revert "starting vault right after installation"

- scripts/installCore.sh
- scripts/remote/system_configs.sql
https://github.com/Shippable/base/issues/37
> Adds script to create systemConfigs table

- scripts/installCore.sh
- scripts/remote/system_configs.sql
- scripts/remote/system_configs_data.sql
Closes https://github.com/Shippable/base/issues/37
> Updates files to insert systemConfig

- scripts/installCore.sh
fixes https://github.com/Shippable/base/issues/38
Could only test after removing ```-c blowfish``` in ssh of rsync commands from scripts/_copyScriptRemote,sh as rsync commands were failing with unknown cipher blowfish errors.
> Show prompt to copy migrations.sql

- data/machines.json
- data/state.json
- scripts/installCore.sh
- scripts/remote/gitlab.rb
fixes https://github.com/Shippable/base/issues/43
> Adds gitlab configuration

- data/state.json
https://github.com/Shippable/base/issues/47
> Renames systemConfigs to systemSettings

- scripts/bootstrapMachines.sh
https://github.com/Shippable/base/issues/58
> Include group in state.json machines

- scripts/installCore.sh
Closes https://github.com/Shippable/base/issues/47
> Updates files to store dbUrl, dbUsername, dbPassword in systemSettings

- scripts/installCore.sh
closes https://github.com/Shippable/base/issues/51
> Once Gitlab boots up, update state.json

- scripts/installCore.sh
https://github.com/Shippable/base/issues/48
> Save RabbitMQ config to state.json

- base.sh
- scripts/_copyScriptLocal.sh
- scripts/installCore.sh
- scripts/remote/bootstrapVault.sh
https://github.com/Shippable/base/issues/49
> Add vault token and vault url to state.json

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/53
> wait for api to boot

- data/state.json.example
- scripts/installCore.sh
- https://github.com/Shippable/base/issues/66
> fixing wokrer token workflow

- base.sh
- scripts/getConfigs.sh
- scripts/installCore.sh
- https://github.com/Shippable/heap/issues/368
> added logging 

- base.sh
- scripts/_copyScriptLocal.sh
- scripts/installCore.sh
- scripts/remote/bootstrapVault.sh
- scripts/remote/vaultConfig.json.template
https://github.com/Shippable/base/issues/76
> use vaultConfig.json.template to copy vault config data to state.json

- data/state.json.example
- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
> adding system config generation workflow

- base.sh
- scripts/_copyScriptRemote.sh
- scripts/bootstrapApp.sh
- scripts/getConfigs.sh
- scripts/installCore.sh
- scripts/remote/bootstrapVault.sh
> updating api provision 

- base.sh
- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/remote/bootstrapVault.sh
- scripts/remote/vaultConfig.json
> fixing vault and envs

- scripts/installCore.sh
https://github.com/Shippable/base/issues/55
> more vault fixes

- data/config.json.example
- scripts/bootstrapApp.sh
> fixing api environments

- scripts/bootstrapApp.sh
> enablging system config creation

- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/remote/systemConfigsData.sql.template
> misc fixes

- data/config.json.example
- scripts/bootstrapApp.sh
- https://github.com/Shippable/base/issues/52
> fixing queue list and migrations exec

- scripts/_copyScriptRemote.sh
https://github.com/Shippable/base/issues/71
> checking whether the number of args are 3

- scripts/remote/installPostgresql.sh
https://github.com/Shippable/base/issues/82
> fixing the permission denied warnings

- .gitignore
- scripts/installCore.sh
Fixes https://github.com/Shippable/base/issues/99
> Fix error on swarm init

- data/config.json.example
Closes https://github.com/Shippable/base/issues/98
> Updates config.json.example to the template for github

- scripts/getConfigs.sh
Closes https://github.com/Shippable/base/issues/104
> Updates getConfigs to append systemIntegrations to state.json

- data/config.json.example
https://github.com/Shippable/base/issues/102
> jobTrigger env added

- scripts/remote/bootstrapVault.sh
https://github.com/Shippable/base/issues/109
> vaultToken updated in systemSettings when Vault is unsealed and running

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/106
> Wait 60s for API to come up

- data/state.json.example
- scripts/installCore.sh
https://github.com/Shippable/base/issues/113
> adding redisUrl to state.json

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/103
> Add a generic handler for provisioning services

- data/config.json.example
- scripts/bootstrapApp.sh
Fixes https://github.com/Shippable/base/issues/107
> Insert system integrations

- base.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/103
> Provision sync

- data/config.json.example
Fixes https://github.com/Shippable/base/issues/115
> Add docker hub to config example json

- data/config.json.example
- data/state.json.example
- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
https://github.com/Shippable/base/issues/120
> Rename braintreeEnabled to serverEnabled.

- data/config.json.example
https://github.com/Shippable/base/issues/102
> adding cron envs

- data/config.json.example
https://github.com/Shippable/base/issues/102
> adding ec2 env

- data/config.json.example
https://github.com/Shippable/base/issues/102
> adding versionTrigger envs

- base.sh
- scripts/upgrade.sh
- https://github.com/Shippable/one/issues/724
> adding upgrade script

- scripts/getConfigs.sh
- scripts/installCore.sh
- https://github.com/Shippable/base/issues/115
> fixing statefile writes

- data/config.json.example
- data/state.json.example
- scripts/getConfigs.sh
https://github.com/Shippable/base/issues/145
> Updates files to store providers

- scripts/installCore.sh
Closes https://github.com/Shippable/base/issues/148
> Leave swarm before attempting to join again

- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/150
> Try to remove service

- data/config.json.example
- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/132
Fixes https://github.com/Shippable/base/issues/133
Fixes https://github.com/Shippable/base/issues/134
Fixes https://github.com/Shippable/base/issues/135
Fixes https://github.com/Shippable/base/issues/136
Fixes https://github.com/Shippable/base/issues/137
Fixes https://github.com/Shippable/base/issues/138
> Add pipelines services

- data/config.json.example
- scripts/provisionServices.sh
fixes https://github.com/Shippable/base/issues/139
fixes https://github.com/Shippable/base/issues/140
fixes https://github.com/Shippable/base/issues/141
fixes https://github.com/Shippable/base/issues/142
fixes https://github.com/Shippable/base/issues/143
fixes https://github.com/Shippable/base/issues/144
> adds new microservices

- data/config.json.example
- data/state.json.example
- scripts/bootstrapApp.sh
- scripts/bootstrapMachines.sh
- scripts/getConfigs.sh
- scripts/installCore.sh
https://github.com/Shippable/base/issues/67
> updating statefile with core components installation status

- scripts/bootstrapApp.sh
- scripts/remote/providersData.sql.template
Closes https://github.com/Shippable/base/issues/145
> Updates files to insert providers for github enterprise and bitbucket server

- data/config.json.example
- scripts/provisionServices.sh
Closes https://github.com/Shippable/base/issues/152
> Allow replicas to be specified

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
Closes https://github.com/Shippable/base/issues/160
> Updates files to add execImage

- scripts/installCore.sh
Closes https://github.com/Shippable/base/issues/147
> Run swarm in drain mode

- data/config.json.example
Fixes https://github.com/Shippable/base/issues/131
> Add github and bitbucket enterprise sysInt

- scripts/remote/systemConfigsData.sql.template
Closes https://github.com/Shippable/base/issues/168
> Updates files to update serviceUserToken in accountToken

- data/config.json.example
fixes https://github.com/Shippable/base/issues/170
> Update example config json values

- data/config.json.example
Closes https://github.com/Shippable/base/issues/171
> Updates image versions to latest

- scripts/bootstrapApp.sh
Fixes https://github.com/Shippable/base/issues/175
> Insert route permissions

- scripts/installCore.sh
Closes https://github.com/Shippable/base/issues/177
> Updates file to correct gitlab POST data

- scripts/bootstrapApp.sh
- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
> Add migrations, routePermissions files

- scripts/remote/migrations.sql
Fixes https://github.com/Shippable/base/issues/186
> Add system machine images

- scripts/getConfigs.sh
- scripts/installCore.sh
Fixes https://github.com/Shippable/one/issues/722
> Update gitlab.rb using systemIntegration

- scripts/getConfigs.sh
https://github.com/Shippable/base/issues/189
> prompt user whether to use state.json.backup

- scripts/getConfigs.sh
eliminating duplicate machines
https://github.com/Shippable/base/issues/189
> machines will be repopulatated in bootstrapMachines.sh

- scripts/remote/installGitlab.sh
fixes https://github.com/Shippable/one/issues/723
> pin gitlab version

- data/config.json.example
- scripts/getConfigs.sh
- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/192
Fixes https://github.com/Shippable/base/issues/191
Fixes https://github.com/Shippable/base/issues/197
Fixes https://github.com/Shippable/base/issues/196
> Add slack, email, nf services

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/184
> skipping component and service installation based on status

- scripts/installCore.sh
fixes https://github.com/Shippable/base/issues/93
> add sleep of 30s

- base.sh
Fixes https://github.com/Shippable/base/issues/203
> Update SCRIPT_DIR_REMOTE after RELEASE is set

- scripts/installCore.sh
- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/205
> Fix vortex, redis urls

- scripts/installCore.sh
> Fix incorrect Gitlab, Redis config

- scripts/provisionServices.sh
fixes https://github.com/Shippable/base/issues/211
> fix ini docker version

- scripts/installCore.sh
https://github.com/Shippable/base/issues/209
> Use the DB host for Redis

- base.sh
- scripts/bootstrapMachines.sh
Closes https://github.com/Shippable/base/issues/198
> Updates files to export LC_ALL=C

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/214
> removes the insertion of TRIECS master integration

- scripts/bootstrapApp.sh
- scripts/remote/system_configs.sql
Closes https://github.com/Shippable/base/issues/219
> Updates files to create systemConfigs and insert systemConfigs before api boots up

- scripts/bootstrapApp.sh
Closes https://github.com/Shippable/base/issues/219
> Updates to add delay of 120 seconds

- scripts/bootstrapApp.sh
Closes https://github.com/Shippable/base/issues/220
> Updates bootstrapApp.sh to check api status before running migrations

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
Closes https://github.com/Shippable/base/issues/201
> Updates files to post systemMachineImages

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/remote/credentials
- scripts/remote/installEcr.sh
https://github.com/Shippable/base/issues/224
> Use ECR instead of Docker Hub

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/228
> Deprov API before attempting to bring up a new one

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/228
> restart api after system machine image insert

- data/config.json.example
- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/235
> Renaming awsAccessKey, awsSecretKey in example config

- base.sh
- scripts/getConfigs.sh
https://github.com/Shippable/base/issues/239
> Prompting the user to add a Bitbucket Server integration

- data/config.json.example
- scripts/getConfigs.sh
fixes https://github.com/Shippable/base/issues/236
> dont ask for ecr in config

- README.md
- base.sh
- scripts/_execScriptRemote.sh
- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/provisionServices.sh
- scripts/remote/bootstrapVault.sh
- scripts/remote/checkRequirements.sh
- scripts/remote/installBase.sh
- scripts/remote/installDocker.sh
- scripts/remote/installEcr.sh
- scripts/remote/installGitlab.sh
- scripts/remote/installPostgresql.sh
- scripts/remote/installRabbit.sh
- scripts/remote/installRedis.sh
- scripts/remote/installSwarm.sh
- scripts/remote/installVault.sh
Fixes https://github.com/Shippable/base/issues/237
> Get rid of sudo, replace with sudo -E

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/246
> removes the aws-root and set allowednull to true for subscriptionIntegration foreign key

- helpers/bbs.sh
- scripts/getConfigs.sh
https://github.com/Shippable/base/issues/239
> moving addition of bbserver integration to helpers

- scripts/getConfigs.sh
- scripts/installCore.sh
Also commenting out state.json.backup check
https://github.com/Shippable/base/issues/249
> Prompting user to add proxy for docker

- helpers/bbs.sh
https://github.com/Shippable/base/issues/239
> Asking for public and private bbserver ip

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
> Add no_proxy config and inject into services

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/getConfigs.sh
This needs to be added back later when required.
Fixes #260
> Remove references to domain, domainProtocol.

- data/config.json.example
Fixes https://github.com/Shippable/base/issues/257
> Update services, stepExec image to latest bits

- data/config.json.example
- scripts/remote/migrations.sql
Fixes #253 
@shrivara Let's get this in along with image updates.
> Clean up auth system ints and update migrations

- scripts/installCore.sh
https://github.com/Shippable/base/issues/263
> add gitlab sysInt if not exists

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/265
> use the ecr image for stepExec

- scripts/remote/migrations.sql
Fixes https://github.com/Shippable/base/issues/267
> adding accountTokens after accounts

- data/config.json.example
- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/273
> updating service bits

- data/config.json.example
- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/273
> updating service bits to v4.10.12

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/277
> Corrected provision jsync command.

- scripts/provisionServices.sh
> Revert "Corrected provision jsync command."

- data/config.json.example
- scripts/provisionServices.sh
> Revert "Adds jSync service to installer"

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/285
> adds file resource

- data/config.json.example
- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/277
> Adds jSync.

- data/config.json.example
Fixes https://github.com/Shippable/base/issues/277
> Add jSync queue

- scripts/remote/migrations.sql
Fixes https://github.com/Shippable/base/issues/277
> Added systemCode for jenkinsJob and unstable status.

- scripts/remote/migrations.sql
> create masterIntegration and masterIntegrationFields for artifactory

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/284
> adds CLUSTER masterIntegration

- data/config.json.example
https://github.com/Shippable/base/issues/293
> removes bitbucket env's from base

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/277
> updates builds table to store externalBuildUrl

- data/config.json.example
> Add email integrations examples

- data/config.json.example
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/299
> start timeTrigger service

- data/config.json.example
https://github.com/Shippable/base/issues/301
This will be tested along with the systemConfig changes for dynamicNodeSystemIntegrationId.
> Add aws cloudProvider systemInt to support dynamic nodes.

- data/config.json.example
https://github.com/Shippable/base/issues/301
> adds dynamicNodesSystemIntegrationId to systemSettings

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/298
> adding gmail & mailgun sysInts

- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
- scripts/remote/system_configs.sql
https://github.com/Shippable/api/issues/15211
> adds dynamicNodesSystemIntegrationId in system_configs

- scripts/remote/installPostgresql.sh
> Pin Postgres version

- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/312
> Updates the jFrog api_Key field name to password

- scripts/bootstrapApp.sh
- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
https://github.com/Shippable/base/issues/317
> Update routePermission, migrations

- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
- scripts/remote/system_configs.sql
https://github.com/Shippable/api/issues/15211
> updates installer to have systemNodePrivateKey and systemNodePublicKey in system_configs

- scripts/remote/system_configs.sql
https://github.com/Shippable/base/issues/321
> Update systemConfigs to be alter table for new columns

- data/config.json.example
- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/321
> updating image tags

- scripts/bootstrapApp.sh
- scripts/remote/installBase.sh
- scripts/remote/installDocker.sh
- scripts/remote/installPostgresql.sh
- scripts/remote/installRabbit.sh
- scripts/remote/installRedis.sh
https://github.com/Shippable/base/issues/320
1. Consolidates and adds sources in installBase.sh
2. fixes GPG error warning
3. fixes error when trying to hit API endpoint without proxy, which returns an error and stops the installation script
> Consolidating and adding sources in a single place

- data/config.json.example
- scripts/bootstrapApp.sh
- scripts/remote/systemConfigsData.sql.template
- scripts/remote/system_configs.sql
https://github.com/Shippable/base/issues/325
> Updates installer to add allowSystemNodes, allowCustomNodes and allowDynamicNodes to systemConfigs

- scripts/remote/migrations.sql
Fixes https://github.com/Shippable/base/issues/326
> Drop systemIntegrationId from systemMachineImages

- data/config.json.example
https://github.com/Shippable/base/issues/329
> Added systemNode private and public key fields to conifg.json.example

- scripts/remote/routePermissions.sql
https://github.com/Shippable/base/issues/331
> updates routePermissions.sql

- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
https://github.com/Shippable/base/issues/340
> updates migration.sql & routePermissions.sql

- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
https://github.com/Shippable/base/issues/343
> Remove permissions for member on projects/newBuild

- scripts/remote/migrations.sql
- scripts/remote/routePermissions.sql
https://github.com/Shippable/base/issues/342
> Remove permissions for member on runs/:id/cancel

- scripts/remote/routePermissions.sql
Fixes https://github.com/Shippable/base/issues/346
> Add routePermissions for triggerNewBuildRequest

- data/config.json.example
- scripts/remote/migrations.sql
https://github.com/Shippable/base/issues/354
> Update components to v28

- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/269
> improving readability

- migrations/v4.10.28.sql
Fixes https://github.com/Shippable/base/issues/371
> Update migrations to insert braintree masterInt fields

- migrations/v4.10.28.sql
- scripts/_manageMasterIntegrations.sh
- https://github.com/Shippable/base/issues/376
> 376 manage mi

- migrations/v4.10.28.sql
- scripts/_manageMasterIntegrations.sh
- scripts/_manageProviders.sh
- scripts/bootstrapApp.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/378
> 378 manange providers

- migrations/v4.10.28.sql
- scripts/_manageProviders.sh
- scripts/_manageSystemIntegrations.sh
- scripts/bootstrapApp.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/379
> 379 manage si

- usr/state.json.example
Fixes https://github.com/Shippable/base/issues/387
> Fix invalid JSON in state example

- scripts/getConfigs.sh
https://github.com/Shippable/base/issues/388
> skip check whether machines.json exists

- scripts/bootstrapApp.sh
Fixes https://github.com/Shippable/base/issues/392
> Create AWS directory if it doesn't exist

- migrations/v4.10.29.sql
https://github.com/Shippable/base/issues/394
> migrations for v4.10.29

- scripts/_manageServices.sh
https://github.com/Shippable/base/issues/362
https://github.com/Shippable/base/issues/364
> adding required services to state.json

- base.sh
- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/400
> provisioning services

- migrations/v4.10.29.sql
- https://github.com/Shippable/base/issues/382
> setting provider requirement condition to false

- migrations/v4.10.29.sql
> Remove systemMachineImage insertion in migration

- migrations/v4.10.29.sql
- scripts/_manageMasterIntegrations.sh
- scripts/_manageSystemIntegrations.sh
- scripts/bootstrapApp.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/379
> fixing migrations and systemIntegrations

- scripts/_manageServices.sh
https://github.com/Shippable/base/issues/362
> removing the error message

- migrations/v4.10.29.sql
- migrations/v4.10.30.sql
Fixes https://github.com/Shippable/base/issues/419
Reverted a change I made locally to v29's sql file.
> Added migrations.sql for the next release.

- scripts/bootstrapApp.sh
- versions/v4.10.29.json
https://github.com/Shippable/base/issues/397
> POST systemMachineImage from versions

- scripts/_manageSystemIntegrations.sh
- scripts/installCore.sh
https://github.com/Shippable/base/issues/416
> Adding gitlab & aws systemIntegrations

- scripts/_manageServices.sh
- scripts/installCore.sh
https://github.com/Shippable/base/issues/362
> add service for masterIntegrations

- usr/state.json.example
https://github.com/Shippable/micro/issues/3920
> adding bitbucketServer scm

- versions/v4.10.29.json
https://github.com/Shippable/base/issues/414
> add envs for s3 credentials

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/414
> adds s3 credentials envs

- migrations/v4.10.29.sql
- migrations/v4.10.30.sql
https://github.com/Shippable/base/issues/382
> update isRequired to false for auth for existing integrations

- scripts/_manageServices.sh
- scripts/installCore.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/364
> Removing services which aren't required

- scripts/bootstrapMachines.sh
- scripts/remote/setupNode.sh
Fixes https://github.com/Shippable/base/issues/428
> Configure ulimits on nodes

- scripts/installCore.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/416
https://github.com/Shippable/base/issues/431
> removing adding systemIntegrations from code

- scripts/bootstrapApp.sh
- usr/state.json.example
Fixes https://github.com/Shippable/base/issues/430
> Run migrations only if it exists

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/434
> cleaning up service status

- base.sh
https://github.com/Shippable/base/issues/367
> Adding -r flag

- base.sh
https://github.com/Shippable/base/issues/436 basic functionality
> adding -f flag

- base.sh
https://github.com/Shippable/base/issues/436
> adding tab of 2 spaces

- scripts/_manageSystemIntegrations.sh
- scripts/bootstrapApp.sh
- scripts/bootstrapMachines.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/431
> fixing gitlab integration

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/443
https://github.com/Shippable/base/issues/364
> removing services in prod assuming installer is running in swarm machine

- migrate.sh
- https://github.com/Shippable/base/issues/449
> adding migration script

- migrate.sh
- https://github.com/Shippable/base/issues/449
> fixing migration

- migrate.sh
- https://github.com/Shippable/base/issues/449
> adding db migration

- migrations/v4.10.32.sql
This contains the contents of the v29 migrations and an additional route permission for PUT systemMachineImages.
https://github.com/Shippable/api/issues/15520
> Add new migration for next release

- base.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/460
> use latest version file

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/397
> PUTting & POSTing sysMachineImages

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/446
> Restart API on local

- migrations/v4.10.31.sql
https://github.com/Shippable/base/issues/470
> create a new master/system integration set of type artifact

- versions/v4.10.28.json
- versions/v4.11.3.json
https://github.com/Shippable/base/issues/479
> removing replicas from api & www

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/472
> adds isFreeUser to routePermissions

- migrations/v4.11.3.sql
- usr/state.json.example
https://github.com/Shippable/api/issues/15526
> rename to accessKey and accessSecret

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/486
> adding a delay of 30s after removing www service

- migrations/v4.11.3.sql
#491 
Adds a index on `projectId` to subscriptionIntegrationPermissions, renames the `roleCode` foreign key on routePermissions, and adds `NOT NULL DEFAULT false` to `resources.isConsistent` and `routePermissions.isPublic`.
> #491; updates to match API models.

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/499
> Adds routePermission for getBuildSatusBySubscriptionId

- versions/v4.10.28.json
- versions/v4.11.3.json
https://github.com/Shippable/base/issues/510
> adding irc to serviceConfigs

- scripts/provisionServices.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/512
> making IRC_BOT_NICK customizable

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/514
> Adds subnetId column in systemMachineImages table

- scripts/bootstrapMachines.sh
https://github.com/Shippable/base/issues/515
> create ssh keys in local

- scripts/bootstrapApp.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/516
> adding systemNodePrivateKey & systemNodePublicKey to systemSettings

- usr/state.json.example
https://github.com/Shippable/base/issues/522
> updates the sample state.json.example in the installer to add subnetd in the system machine image

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/524
> Change subnetId to not null for systemMachineImages

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/500
> crop cachingEnabled from systemCofigs

- migrations/v4.11.3.sql
> Revert "Change subnetId to not null for systemMachineImages"

- migrations/v4.11.3.sql
https://github.com/Shippable/api/issues/15596
> removes NOT NULL from systemMachineImages.subnetId

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/475
> adds the routePermissions for passthrough/jobs/:id/reports

- scripts/provisionServices.sh
- versions/v4.10.28.json
- versions/v4.11.3.json
https://github.com/Shippable/base/issues/535
> adding volumes, if present

- scripts/provisionServices.sh
- scripts/remote/installDocker.sh
- versions/v4.10.28.json
- versions/v4.11.3.json
Installs a lower version of Docker which can run builds and also adds TRUCK locally
Fixes #536
> Allow builds to run locally

- scripts/remote/installDocker.sh
- versions/v4.10.28.json
- versions/v4.11.3.json
https://github.com/Shippable/base/issues/535
> Adding correct volumes for ec2

- scripts/remote/installDocker.sh
Fixes https://github.com/Shippable/base/issues/540
> Do not configure Docker on local

- scripts/installCore.sh
- scripts/remote/installDocker.sh
> Restore handling of docker installation

- versions/v4.10.28.json
https://github.com/Shippable/base/issues/535
removing volumes as per comment in v4.10.28.json
> removing volumes as this is not supported

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/552
> update post/put SMIs logic

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/555
> Updates file to insert dynamicNodesSystemIntegrationId

- scripts/bootstrapApp.sh
- scripts/installCore.sh
- scripts/remote/config.json
- https://github.com/Shippable/base/issues/547
> using aws credentials helper for login

- scripts/bootstrapApp.sh
- scripts/installCore.sh
https://github.com/Shippable/base/issues/547
> moving docker login to core installation

- docs/Readme.md
- docs/production.md
- docs/state.md
- https://github.com/Shippable/pm/issues/6935
> adding state file information

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/564
> adds route permissions for post /v2/versions

- versions/v4.11.3.json
https://github.com/Shippable/base/issues/566
> removing DOCKER_VERSION & SETUP_RUN_SH envs from ini

- docs/production.md
- scripts/installCore.sh
- scripts/provisionServices.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/568
> pulling images on all hosts before running service

- scripts/provisionServices.sh
- https://github.com/Shippable/base/issues/568
> quoting the remote exec command

- usr/state.json.example
changing customHostDockerVersion from 1.12.1 to 1.9.1
> using docker version 1.9.1

- migrations/v4.11.3.sql
https://github.com/Shippable/base/issues/574
> adds system code for mktg and master intergration for hubspot

- migrations/v4.11.3.sql
- usr/state.json.example
- versions/v4.11.3.json
> add irc masterInt and make it an int service

- migrations/v4.11.3.sql
> fix end if and update irc to account level

- scripts/provisionServices.sh
- usr/state.json.example
- versions/v4.11.3.json
https://github.com/Shippable/base/pull/577
> updates installer to add hubspot systemIntegration example

- migrations/v4.12.0.sql
- https://github.com/Shippable/base/issues/589
> adding routes for accounts

- migrations/v4.12.0.sql
- https://github.com/Shippable/api/issues/15632
> adding route roles for GET /subscriptions

- scripts/provisionServices.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/607
> Updates files to set shippableAwsAccountId for IAM access

- base.sh
- scripts/_checkApiHealth.sh
- scripts/bootstrapApp.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/605
> adding apiTimeout

- scripts/local/vault/scripts/system_configs_data.sql
Fixes https://github.com/Shippable/base/issues/609
> Remove stray sql file

- scripts/bootstrapApp.sh
https://github.com/Shippable/pm/issues/7004
> adding sleep 30 after api stop

- .gitignore
- base.sh
Fixes https://github.com/Shippable/base/issues/618
> Dump output logs

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/615
> adds route_roles for accountTokens

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/620
> adding set_route_role for accountCards

- migrations/v4.12.1.sql
fixes https://github.com/Shippable/base/issues/623
> adds account profile role codes

- migrations/v4.12.1.sql
from https://github.com/Shippable/base/issues/623
> fixes role bugs for accountProfile routes

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15787
> adds the routeRoles for accountIntegration

- migrations/v4.12.1.sql
from https://github.com/Shippable/base/issues/623
> remove role code for super user only account profile routes

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/616
> Adds migration for /accountIntegrations routeRoles

- scripts/_manageSystemMachineImages.sh
- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/631
> Updates files to compare systemMachineImages based on name

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/630
> adds route roles for providers and move accountTokens to alphabetical order

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15853
> adds the routeRoles for masterIntegrations

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15863
> adds masterIntegrationFields routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/640
> Adds new routeRoles for systemMachineImages getS and getById routes

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/643
> adds route role for plans

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/644
> add routeRole for systemNodes #644

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15910
> adds clusterNodes getS routeRole

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/649
> adds route roles for projectAccounts

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/655
> adds routeRoles for passthrough

- scripts/_manageSystemMachineImages.sh
- usr/state.json.example
https://github.com/Shippable/base/issues/661
> Updates _manageSystemMachineImages to pick execImage and runShImage values from deploy tag

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/664
> adding /payments/clienttoken to routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/663
> adds routeRoles from transactions

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/668
> route roles for gets clusterNodes.

- migrations/v4.12.1.sql
> add routeRoles for runs

- migrations/v4.12.1.sql
- https://github.com/Shippable/api/issues/16005
> adding clusternode stats GET route roles

- migrations/v4.12.1.sql
> add roles for /jobs/:jobId

- migrations/v4.12.1.sql
fixes https://github.com/Shippable/base/issues/666
> Add route poles for post systemNodStats

- base.sh
- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
Fixes https://github.com/Shippable/base/issues/660
> Use :latest deploy tag

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/663
> updates subscriptions/:id/transactions routerole to subscriptions/:subscriptionId/transactions

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/644
> set routeRoles for /systemNodes/:id GET & PUT

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15749
> adds the routeRoles for POST /jobTestReports

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16023
https://github.com/Shippable/base/issues/649
> adds routeRoles for projectAccounts and subscriptionsAccounts

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/683
> Adds routeRoles for GET /clusterNodes/:id

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/681
Ran the migrations locally in db
routeRoles were getting added
> adds routeRoles for jobDependencies

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16024
https://github.com/Shippable/api/issues/16025
> adds routeRoles for jobCoverageReports

- migrations/v4.12.1.sql
Also, fixes indentation in other places.
Fixes #688
> Add clusterNodes/:id/validate routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/690
> Adds routeRoles for GET /clusterNodes/:id/initScript

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/692
> adds superUsers routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/694
> Updates files to add routeRoles for DELETE /clusterNodes/:id

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16034
https://github.com/Shippable/api/issues/16033
> adds the routeRoles for GET, POST subsciptionIntegrations

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/697
> Add routeRoles for PUT /clusterNodes/:id

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/697
> Adds role for publicUser

- migrations/v4.12.1.sql
Fixes #https://github.com/Shippable/base/issues/699
> Add routeRoles for POST clusterNodes

- migrations/v4.12.1.sql
Fixes https://github.com/Shippable/base/issues/702
> Add routeRoles for /clusterNodes/:id/status

- migrations/v4.12.1.sql
from https://github.com/Shippable/base/issues/644
> add routeRoles for system node validate

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/705
> adds routeRoles for clusterNodeStats

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/707
> adding route role for POST /systemNodes/:id/status

- migrations/v4.12.1.sql
Fixes https://github.com/Shippable/base/issues/713
> Replace :id with :clusterNodeId

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/711
> adds routeRoles for buildJobs object

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/710
> Adds routeRoles for GET /versions/:versionId

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/718
> changes :id to clusterNodeId and clusterNodeStatId

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/716
> Adds routeRoles for DELETE /version/:id

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16082
> adds the delete /jobTestReports/:id roleRoutes

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/718
> removes routeRole DEL clusterNodeStats/:clusterNodeStatId

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/718
> removes /clusterNodeStats/:clusterNodeStatId routeRole

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/724
> adds migration routeRoles for build object

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16110
> adds the roleRoutes for GET /jobTestReports

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15769
> using :systemNodeId instead of :id in base/migrations

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/733
> Adds routeRoles for POST /versions /v2/versions

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/15734
> using :accountCardId instead of :id

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/735
> Adds routeRoles for GET /versions

- migrations/v4.12.1.sql
fixes https://github.com/Shippable/base/issues/738
> add route roles for runs

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/735
> Rearranges routeRoles for versions

- migrations/v4.12.1.sql
from https://github.com/Shippable/base/issues/722
> adds support for runs cancel

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/722
> setting routeRoles for DELETE /runs/:runId

- migrations/v4.12.1.sql
- https://github.com/Shippable/api/issues/16147
> adding route roles for GET subscription integrations

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16148
> adding route roles for GET subscriptionIntegrations/:subscriptionIntegrationId

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16171
> adds routeRoles for projects object

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/748
> adds jobConsoles routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/722
> adding routeRoles for /projects/:projectId/branchRunStatus

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/722
> updating routeRoles for /accounts/:accountId/runStatus

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/754
> adds routeRoles for buildJobConsoles

- migrations/v4.12.1.sql
- https://github.com/Shippable/api/issues/16149
> adding permissions for PUT subscriptionIntegrations

- migrations/v4.12.1.sql
- https://github.com/Shippable/api/issues/16150
> adding permissions for DELETE /subscriptionIntegrations

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16220
> fixes accountIntegration to use correct :id conventions

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/764
> adds the role code of public user for jobConsoles

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/762
> Creates routeRoles for projects/:projectId/decrypt

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/766
> added memeber role for susbcriptions/:id/encrypt

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16241
> updates routeRoles to rename :id to :accountTokenId

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/770
> update jobDependencies and subscriptionIntegrationPermissions to use the convention routeObject/:routeObjectId

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16252
> renames :id to providerId in routeRoles

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16260
> update discounts passthrough routeRole to new pattern

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16260
> renames :id to :jobId in /passthrough/jobs/:id/reports

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16264
> removing routeRoles for superUsers(6080)

- migrations/v4.12.1.sql
> Add jobCoverage report roles

- migrations/v4.12.1.sql
from https://github.com/Shippable/base/issues/722
> adds subs/:id/runStatus

- migrations/v4.12.1.sql
fixes https://github.com/Shippable/base/issues/722
> move runs post to validateProjects

- migrations/v4.12.1.sql
https://github.com/Shippable/api/issues/16317
ran the migrations in local and the routeRoles were getting added
> adds routeRoles for triggerNewBuildRequest

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/784
> adding 6040 routeRole to public routes

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/786
> Drops routePermissions table

- base.sh
- scripts/cleanup.sh
- scripts/remote/cleanup.sh
- https://github.com/Shippable/base/issues/789
> adding scripts to remove stale images

- scripts/cleanup.sh
- https://github.com/Shippable/base/issues/789
> fixing incorrect quotes

- scripts/cleanup.sh
- https://github.com/Shippable/base/issues/789
> fixing micro repo cleanup

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/793
> adds routeRoles for jobDependencies getById

- migrations/v4.12.1.sql
> fixes #795 : removing unused daily agg fields

- migrations/v4.12.1.sql
https://github.com/Shippable/base/issues/797
ran the migrations in local
> adds lastVersionId and lastVersionName coloumns to resources in migrations and foreign key relationship to versions id

- migrations/v4.12.1.sql
> write migration script to populate new fields in exiting resources 

- migrations/v4.12.2.sql
- versions/v4.12.2.json
https://github.com/Shippable/base/issues/801
> Adds versions/migrations for v4.12.2

- migrations/v4.12.2.sql
https://github.com/Shippable/base/issues/803
> add new field addOnMinionCount and addOnMinionCountOverridden to subscription

- migrations/v4.12.2.sql
Fixes https://github.com/Shippable/base/issues/805
> Adds subscriptionId column to clusterNodeConsoles

- migrations/v4.12.2.sql
https://github.com/Shippable/base/issues/809
> adds skipped status for buildJobs

- migrations/v4.12.2.sql
https://github.com/Shippable/base/issues/811
> removes account/id/sync routeRole

- migrations/v4.12.2.sql
Fixes https://github.com/Shippable/base/issues/813
> Adds migration for systemNodeStats/clusterNodeStats

- migrations/v4.12.2.sql
Fixes https://github.com/Shippable/base/issues/815
> Updates POST /clusterNodeStats /systemNodeStats route to be public

- migrations/v4.12.3.sql
- versions/v4.12.3.json
> Adds version v4.12.3

- scripts/installCore.sh
- scripts/remote/installNTP.sh
> install NTP on service machines 

- migrations/v5.0.0.sql
- versions/v5.0.0.json
Fixes https://github.com/Shippable/base/issues/822
> Adds versions + migrations for 5.0.0

- scripts/installCore.sh
https://github.com/Shippable/base/issues/824
> get machines from state file instead of ENV

- migrations/v5.1.0.sql
https://github.com/Shippable/base/issues/828
Verified locally by creating a apiToken and using that for project webhook integration.
yml: https://github.com/deepikab93/sample/blob/master/shippable.yml
> Add new routeRole freeUser for /projects/:projectId/newBuild route

- migrations/v5.0.0.sql
Verified that the routes get deleted and migrations run successfully.
Fixes #829
> Remove postClusterNodeStatus, postSystemNodeStatus routeRoles

- migrations/v5.0.0.sql
> Revert "Remove postClusterNodeStatus, postSystemNodeStatus routeRoles"

- migrations/v5.1.0.sql
https://github.com/Shippable/base/issues/834
> Fixes info logs when trying to delete a table which doesn't exist

- migrations/v5.1.0.sql
https://github.com/Shippable/base/issues/834
> Adds checks for indexes

- migrations/v5.1.0.sql
Fixes https://github.com/Shippable/base/issues/834
> Checks for fk relations

- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/834
> Adds checks before inserting systemConfigs table

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/841
> drop superUsers and betaUsers tables

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/840
> add new field builderAccountId to projects schema

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/845
> adds /v2/subscriptions/:subscriptionId/billing routeRoles

- migrations/v5.1.1.sql
> adds FK_relations for projects 

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/844
also adding systemCodes 6090 & 6100 for betaUser & serviceUser respectively.
> adding script to move accounts.systemRoles to accountRoles

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/853
> adding 6060 routeRole for GET /accountRoles

- scripts/bootstrapMachines.sh
- https://github.com/Shippable/base/issues/855
> add flags to track machine installation

- migrations/v5.1.1.sql
- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
> Remove Vault account token, refresh related fields

- usr/system_configs.sql.template
> Remove unused field

- scripts/bootstrapApp.sh
- usr/system_configs.sql.template
https://github.com/Shippable/micro/issues/4357
> removes cloudProviders from systemConfigs

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/860
> drop systemRoles columns from accounts

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/844
> adding serviceUser role

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/867
> add resource type codes for ciRepo and ciJob

- base.sh
- https://github.com/Shippable/pm/issues/7497
> adding message for successful installation

- scripts/_checkApiHealth.sh
> Exit with error on API timeout

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
- https://github.com/Shippable/base/issues/876
> creating and setting default value for global s3 bucket

- migrations/v5.1.1.sql
- https://github.com/Shippable/api/issues/16654
> adding isConsolesArchived column to jobs

- migrations/v5.1.1.sql
- https://github.com/Shippable/api/issues/16654
> grammar fix

- migrations/v5.1.1.sql
https://github.com/Shippable/base/issues/884
> adds masterIntegration for kubernetes

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/882
Cleared `"services": [ ]` in state.json. After running base installer, `services` got populated with all env's of each service.
> pull images before upgrading

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/882
Tested locally, by making `"services": [ ]` and then ran the base installer.
> save_service_configs for are the services for local

- scripts/provisionServices.sh
- usr/state.json.example
- versions/v5.1.1.json
#888 
Adds `provision` to match `manifest`.  Locally, this (and some changes to `usr/state.json`) results in a running `provision` container.
> #888; adds provision stepExec microservice.

- migrations/v5.1.2.sql
- https://github.com/Shippable/api/issues/16655
> adding route role for job console artifacts

- migrations/v5.1.2.sql
Fixes https://github.com/Shippable/base/issues/894
> Removes projects/:projectId/sync routeRoles

- migrations/v5.1.2.sql
Fixes https://github.com/Shippable/base/issues/896
> Drops projects.isSyncing column

- base.sh
Fixes https://github.com/Shippable/base/issues/898
> Ensure state.json is valid JSON before install

- usr/state.json.example
- versions/v5.1.2.json
Fixes https://github.com/Shippable/base/issues/900
> Add logup as a core service

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/892
1. Stop all  stateless services
2. Upgrade  statefull services
3. Upgrade  stateles services.
> Update base installer to stop all stateless services before upgrading

- versions/v5.1.2.json
https://github.com/Shippable/base/issues/892
> remove unused envs

- scripts/bootstrapApp.sh
- https://github.com/Shippable/pm/issues/7537
> fixing bug where root bucket is not getting set

- migrations/v5.1.3.sql
https://github.com/Shippable/base/issues/905
> adds route roles for project createCi route

- migrations/v5.1.4.sql
Fixes https://github.com/Shippable/base/issues/908
> Adds isConsoleArchived column to buildJobs

- migrations/v5.1.4.sql
Fixes https://github.com/Shippable/base/issues/910
> Adds routeRoles for /buildJobs/:buildJobId/artifactUrl

- migrations/v5.1.4.sql
- https://github.com/Shippable/api/issues/16730
> adding route role for project artifact route

- migrations/v5.1.5.sql
- https://github.com/Shippable/api/issues/16752
> adding route roles for job coverage and test reports

- scripts/bootstrapApp.sh
https://github.com/Shippable/base/issues/917
> ensure psql returns error code, if any

- migrations/v5.1.5.sql
https://github.com/Shippable/base/issues/919
> Allow GHE auth integration to be created without providerId

- scripts/bootstrapApp.sh
> Skip image pull if its already pulled

- migrations/v5.1.5.sql
- usr/state.json.example
- versions/v5.1.5.json
> Rename auth integration from githubEnterprise to ghe

- scripts/_copyScriptLocal.sh
- scripts/_copyScriptRemote.sh
- scripts/_execScriptRemote.sh
> Remove quiet flags from rsync, ssh commands

- scripts/_manageSystemMachineImages.sh
> replace runSh with genexec

- migrations/v5.2.1.sql
- scripts/_manageServices.sh
- https://github.com/Shippable/base/issues/937
> 937 add typecode for generic master integrations

- scripts/_manageServices.sh
https://github.com/Shippable/pm/issues/7449
> patching v5.1.5 to fix services removal when they are removed from state

- migrations/v5.2.1.sql
- usr/state.json.example
- https://github.com/Shippable/base/issues/938
- https://github.com/Shippable/base/issues/939
- tested by adding the integration in state.json and removing it. this successfully enables/disables the integration in database
> adding new master integration

- scripts/_manageSystemIntegrations.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/940
> 940 add filestore systemintegration

- usr/state.json.example
- https://github.com/Shippable/base/issues/940
> fixing state.json example

- usr/state.json.example
- versions/v5.2.1.json
https://github.com/Shippable/base/issues/945
> Adds KUBERNETES integration in required places

- migrations/v5.2.1.sql
- usr/state.json.example
- https://github.com/Shippable/base/issues/951
> adding master integration and fields for gitlab credentials

- migrations/v5.2.1.sql
- usr/state.json.example
- https://github.com/Shippable/base/issues/952
> adding systemintegation for state store

- migrations/v5.2.1.sql
- https://github.com/Shippable/base/issues/955
> adding master integration and fields for notification providers

- migrations/v5.2.1.sql
- usr/state.json.example
- versions/v5.2.1.json
- https://github.com/Shippable/base/issues/956
> 956 add system integrations

- scripts/_manageSystemIntegrations.sh
https://github.com/Shippable/base/issues/959
> deleting systemIntegrations from db, which are deleted from state.json

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/966
> add new field proxyBuildJobPropertyBag in jobs schema

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/961
> adding column isOrphaned

- base.sh
- migrations/post_install/v5.2.3-post_install.sql
- scripts/bootstrapApp.sh
- scripts/cleanup.sh
https://github.com/Shippable/base/issues/962
> db cleanup, after install complete

- migrations/v5.2.3.sql
- scripts/_manageSystemMachineImages.sh
https://github.com/Shippable/base/issues/968
> Drop execImage from systemMachineImages

- migrations/v5.2.3.sql
- https://github.com/Shippable/base/issues/973
> adding master integration for braintree

- usr/state.json.example
- https://github.com/Shippable/base/issues/974
> adding braintree system integration template

- usr/state.json.example
- https://github.com/Shippable/base/issues/974
> removing redundant integrations

- migrations/v5.2.3.sql
- usr/state.json.example
- https://github.com/Shippable/base/issues/978
> adding master integrations for auth

- usr/state.json.example
- https://github.com/Shippable/base/issues/979
> adding examples of auth integrations

- versions/v5.2.3.json
https://github.com/Shippable/pm/issues/7781
> Cleanup of unused env vars for www

- migrations/v5.2.3.sql
- usr/state.json.example
> Add migrations for systemMachineImages.drydockTag

- usr/state.json.example
- https://github.com/Shippable/base/issues/986
> adding provision integration for setting up dynamic nodes

- scripts/_manageSystemIntegrations.sh
- https://github.com/Shippable/base/issues/986
> fixing system integration upsert logic

- migrations/v5.2.3.sql
- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
- https://github.com/Shippable/base/issues/988
> removing "dynamicNodeSystemIntegrationsId" from  installer

- migrations/v5.2.3.sql
- versions/v5.2.3.json
- https://github.com/Shippable/base/issues/992
> adding hubspot integration and fixing versions file

- usr/state.json.example
- https://github.com/Shippable/base/issues/993
> fixing hubspot integration name

- migrations/v5.2.3.sql
Any related sysInt has to be cleaned up before, so that its cleaned up from Vault as well.
https://github.com/Shippable/base/issues/985
> Drop S3 artifacts masterIntegration

- migrations/v5.2.3.sql
https://github.com/Shippable/pm/issues/7810
> Adds missing end if statement

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/999
https://github.com/Shippable/base/issues/1000
> adds systemCodes for ciYmlIntegration group and add alias column to masterIntegrations table

- migrations/v5.2.3.sql
https://github.com/Shippable/api/issues/16887
> adds the masterIntegrationMap routeRoles

- migrations/v5.2.3.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1003
> adds sshKeys integration

- migrations/v5.2.3.sql
- https://github.com/Shippable/base/issues/996
> removing redundant master integrations and fields

- migrations/v5.2.3.sql
- scripts/_manageSystemIntegrations.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/996
> dropping redundant columns from system integration

- migrations/v5.2.3.sql
- https://github.com/Shippable/base/issues/996
> removing providers with integrations

- scripts/_manageSystemIntegrations.sh
- https://github.com/Shippable/base/issues/996
> remove redundant code

- migrations/v5.2.3.sql
- https://github.com/Shippable/pm/issues/7748
> dropping master integrationid dependency from providers

- migrations/v5.2.3.sql
https://github.com/Shippable/api/issues/16887
> updates the table name to masterIntegrationTypeCodes

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1012
> remove masterIntegrationId from insert into providers

- migrations/v5.2.3.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1018
> adds emailCreds masterIntegration

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1005
> Adds masterIntegrationTypeCodes for sshKeys integration

- base.sh
- scripts/bootstrapApp.sh
To track how much time migrations etc. take.
> Add timestamp in process marker

- migrations/v5.2.3.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1015
> adds hipchatCreds masterIntegration

- migrations/v5.2.3.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1022
> adds slackCreds masterIntegration

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1024
> adds entry for emailCreds masterIntegration in masterIntegrationTypeCodes

- usr/state.json.example
> Add www.signals to rootQueueList

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1025
> adds hipchatCreds masterIntTypeCodes

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1038
> Drop mailChimpId, welcomeEmailSent, isSuperUser, isBetaUser and isOpsUser from accounts

- migrations/v5.2.3.sql
- usr/state.json.example
> Add gitlabKeys master integration

- scripts/bootstrapApp.sh
- usr/system_configs.sql.template
> Set defaults, not null in systemConfigs

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
- https://github.com/Shippable/base/issues/1032
> adding field to store node scripts location

- migrations/v5.2.3.sql
https://github.com/Shippable/base/issues/1043
> Adds systemCodes for jobStatesMapType, jobStatesMapContextType and routeRoles.

- migrations/v5.2.3.sql
- https://github.com/Shippable/api/issues/16938
> adding route role for passthrough route

- usr/state.json.example
- https://github.com/Shippable/api/issues/16938
> fixing default value of node init script location

- scripts/_copyScriptRemote.sh
- scripts/bootstrapApp.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/1049
> copying scripts to db host if running in server mode

- scripts/bootstrapApp.sh
- https://github.com/Shippable/base/issues/1049
> fixing db scp arguments

- scripts/bootstrapApp.sh
- https://github.com/Shippable/base/issues/1049
> fixing db ip

- scripts/bootstrapApp.sh
- https://github.com/Shippable/base/issues/1049
> fixing logic for setting nodeScriptsLocation

- migrations/post_install/v5.2.4-post_install.sql
https://github.com/Shippable/base/issues/1058
> updating isOrphaned script

- base.sh
- migrations/master.sql
- migrations/post_install/master-post_install.sql
- scripts/bootstrapApp.sh
- versions/master.json
> Add 'master' version

- usr/state.json.example
https://github.com/Shippable/base/issues/1067
> removes stale masterIntegrations

- base.sh
- scripts/bootstrapApp.sh
- scripts/logger.sh
- scripts/provisionServices.sh
- scripts/remote/installDocker.sh
https://github.com/Shippable/base/issues/1074
> Install Docker 1.13.1 and remove wait times

- migrations/master.sql
https://github.com/Shippable/base/issues/1072
> adds views routeRoles and adds defaultAccountViewId to account model

- migrations/master.sql
https://github.com/Shippable/base/issues/1072
> resoves typo

- scripts/remote/installDocker.sh
> Make Docker install script non-interactive

- scripts/remote/installDocker.sh
> Always use new config for Docker install

- .gitignore
- base.sh
- scripts/_helpers.sh
- https://github.com/Shippable/base/issues/1063
> archiving state file after deployment

- migrations/master.sql
https://github.com/Shippable/base/issues/1081
> Add routeRoles for viewObjects

- migrations/master.sql
Fixes https://github.com/Shippable/base/issues/1050
> add systemCodes for views and viewObjects

- scripts/remote/installDocker.sh
Tested by bringing up a new cluster on DO running an old version and upgrading to a new one.
#1088
> Clean up any existing Docker installation

- migrations/master.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1085
Tested on local
> adds drydockFamily column to systemMachineImages

- scripts/_helpers.sh
> Fix state file archival

- scripts/_helpers.sh
https://github.com/Shippable/base/issues/1094
> Fix one-off bug in state file removal

- migrations/pre_install/master-pre_install.sql
https://github.com/Shippable/base/issues/1093
> adds query to migrate existing subscriptions that have a null value to use the current default image 

- scripts/bootstrapApp.sh
Adding this temporarily until www retries on api call failures.
> Wait for 15s between api restarts

- scripts/bootstrapApp.sh
- usr/state.json.example
- https://github.com/Shippable/base/issues/1080
> removing server enabled flag for setting node scripts location

- migrations/master.sql
https://github.com/Shippable/base/issues/1098
> adds u16* as official images

- migrations/pre_install/master-pre_install.sql
https://github.com/Shippable/base/issues/1093
> updates query to remove subQuery

- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1055
```
-[ RECORD 1 ]-------------------------
code        | 301
name        | branch
group       | jobStatesMapContextType
-[ RECORD 2 ]-------------------------
code        | 302
name        | tag
group       | jobStatesMapContextType
-[ RECORD 3 ]-------------------------
code        | 303
name        | release
group       | jobStatesMapContextType
-[ RECORD 4 ]-------------------------
code        | 304
name        | pr
group       | jobStatesMapContextType
```
> give correct systemCodes

- migrations/master.sql
> Add u14all, u16all as official images

- scripts/_manageSystemIntegrations.sh
fixes: https://github.com/Shippable/base/issues/1110
> gets all the systemInts

- scripts/bootstrapApp.sh
- scripts/remote/installBase.sh
- https://github.com/Shippable/api/issues/17101
> setting node scripts location based on release version

- scripts/remote/cleanup.sh
> Use image id to cleanup to ensure dangling images are removed

- scripts/cleanup.sh
> Skip already clean up image

- scripts/_manageSystemIntegrations.sh
- scripts/_manageSystemMachineImages.sh
> Exit on API errors

- migrations/master.sql
fixes: https://github.com/Shippable/base/issues/1113
> adds urlSlug column to providers

- scripts/_manageMasterIntegrations.sh
- scripts/bootstrapApp.sh
> Don't enable already enabled master integration

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1115
> adding mktgPort column to systemConfig

- versions/master.json
https://github.com/Shippable/base/issues/1127
> adding mktg service

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/1129
> provisioning mktg

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/1129
> cleanup mapping env vars

- scripts/provisionServices.sh
https://github.com/Shippable/base/issues/1129
> provision mktg service only if it is present in state.json

- scripts/bootstrapApp.sh
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1136
> adding mktgUrl systemConfig

- scripts/provisionServices.sh
- versions/master.json
https://github.com/Shippable/base/issues/1129
> provisioning mktg globally

- migrations/master.sql
https://github.com/Shippable/base/issues/1146
> Adds jobStatesMapContextType for runCLI

- usr/state.json.example
https://github.com/Shippable/base/issues/1148
> Add core.segment to rootQueueList

- migrations/master.sql
- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1146
> update script to take runCLI type

- migrations/master.sql
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1144
> Remove references to systemConfigs in migrations

- migrations/master.sql
fixes: https://github.com/Shippable/base/issues/1139
> adds route permissions for providers/urlSlug/:urlSlug

- migrations/master.sql
- usr/state.json.example
- versions/master.json
https://github.com/Shippable/base/issues/1153
> adding master and system integrations for Segment

- migrations/master.sql
https://github.com/Shippable/base/issues/1155
> adds endedAt column in builds

- migrations/master.sql
https://github.com/Shippable/base/issues/1158
> adds migration for /providers getS #1158

- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1156
> migrations for populating endedAt property in builds table

- migrations/master.sql
https://github.com/Shippable/base/issues/1161
> updates migration for urlSlug

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1163
> add segmentMktgKey to system configs

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1168
> removing serverEnabled column from systemConfigs

- migrations/master.sql
- usr/state.json.example
- versions/master.json
https://github.com/Shippable/base/issues/1172
> add master and system integration for clearbit

- migrations/master.sql
https://github.com/Shippable/base/issues/1178
Tested locally by running the migration script.
> adds new field clearbitProfileId to accounts

- migrations/master.sql
Fixes https://github.com/Shippable/base/issues/1180
> Removes systemCodes.propertyBag

- migrations/master.sql
https://github.com/Shippable/base/issues/1182
> dropping cdmContainers, disks, memory columns

- usr/state.json.example
fixes: https://github.com/Shippable/base/issues/1184
> removes www.sockets queue from state.json.example

- migrations/master.sql
https://github.com/Shippable/base/issues/1186
> adds keyValuePair masterIntegration

- migrations/master.sql
> adds new field genericIntegrations to jobs schema 

- usr/state.json.example
- versions/master.json
https://github.com/Shippable/base/issues/1191
> adds mktgDB systemIntegrations

- migrations/master.sql
https://github.com/Shippable/base/issues/1189
> dropping pipelineCount from subscriptions

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1196
> removing defaultPipelineCount from sysConfig

- usr/state.json.example
https://github.com/Shippable/base/issues/1194
> adds segment sysInt with keyValuePair masterInt

- migrations/master.sql
fixes https://github.com/Shippable/base/issues/1199
> remove isAuthorized and enforceScopes from account profiles

- migrations/master.sql
https://github.com/Shippable/base/issues/1200
> removes segmentApiToken from masterIntField and segmentKeys from masterInt

- usr/state.json.example
https://github.com/Shippable/base/issues/1200
> Removes segmentKeys from masterIntegrations

- migrations/master.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1198
> Update Clearbit system integration and remove old master integration

- migrations/master.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1211
> renames `bitbucketserverKeys` to `bitbucketServerKeys` #1211

- versions/master.json
https://github.com/Shippable/base/issues/1217
> start segmentListner as a coreservice

- scripts/_shippableAdapter.sh
https://github.com/Shippable/base/issues/1220
> create the apiResponseBody file before using it

- scripts/_manageSystemIntegrations.sh
- scripts/_manageSystemMachineImages.sh
- scripts/_shippableAdapter.sh
https://github.com/Shippable/base/issues/1215
> using adapter to make GET calls

- scripts/_manageMasterIntegrations.sh
- scripts/_manageSystemIntegrations.sh
- scripts/_manageSystemMachineImages.sh
- scripts/_shippableAdapter.sh
https://github.com/Shippable/base/issues/1222
https://github.com/Shippable/base/issues/1223
https://github.com/Shippable/base/issues/1224
> update PUT, POST, DELETE calls to use adapter

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1205
> removes segmentMktgKey from systemConfigs table

- migrations/master.sql
- usr/state.json.example
https://github.com/Shippable/base/issues/1226
> modifies githubenterpriseKeys to githubEnterpriseKeys #1226

- migrations/master.sql
https://github.com/Shippable/base/issues/1230
> creates index on postgres on lowercase of subscription.orgName

- scripts/bootstrapApp.sh
- usr/system_configs.sql.template
#1232 
Adds the new columns so that they can be added to API.  Tested by running `upgrade` and then re-installing.
> #1232; adds new systemConfigs columns.

- migrations/master.sql
https://github.com/Shippable/base/issues/1235
> creates index on postgres on lowercase of project.fullName

- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1234
> Adds mktgCTAAggs for systemConfigs

- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1228
> add mktgPageAggsLastDtTm to systemConfig

- migrations/master.sql
https://github.com/Shippable/base/issues/1238
> drop index subProviderIdOrgNameI from subscriptions

- migrations/master.sql
https://github.com/Shippable/base/issues/1240
> drops index projProviderIdFullNameI from projects

- usr/state.json.example
https://github.com/Shippable/base/issues/1242
> add dbSchema to mktgDB system integration

- usr/state.json.example
This reverts commit 3b4b662ca6020ffee54f3666c0dc0e294c168843.
https://github.com/Shippable/base/issues/1242
> Revert "add dbSchema to mktgDB system integration"

- migrations/master.sql
Fixes https://github.com/Shippable/base/issues/1247
> Adds execImage column to systemNodes/clusterNodes

- migrations/master.sql
https://github.com/Shippable/base/issues/1249
> creates index on postgres on lowercase of project.name

- migrations/master.sql
https://github.com/Shippable/base/issues/1251
> drops index projProviderIdNameI from projects

- migrations/v5.3.4.sql
only for  project owners
https://github.com/Shippable/base/issues/1253
> add route roles for projects/:projectId/collaborators

- migrations/master.sql
https://github.com/Shippable/base/issues/1253
> adds route roles for projects/:projectId/collaborators

- migrations/v5.3.4.sql
> Revert "add route roles for projects/:projectId/collaborators"

- migrations/master.sql
https://github.com/Shippable/base/issues/1258
> Add earlyAdopterMinionCount in subscriptions

- usr/state.json.example
https://github.com/Shippable/base/issues/1261
> Removes extra comma

- migrations/master.sql
https://github.com/Shippable/base/issues/1263
> creates new indices on buildJobs

- migrations/master.sql
https://github.com/Shippable/base/issues/1265
> creates new indices on builds

- migrations/master.sql
https://github.com/Shippable/base/issues/1267
> creates new index on jobDependencies

- migrations/master.sql
https://github.com/Shippable/base/issues/1269
> creates new index on resources

- migrations/master.sql
https://github.com/Shippable/base/issues/1271
> creates new indices on versions

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
- this change makes sure that overlay network is not used when api,www and mktg services are created
> bypassing overlay network to publish service ports

- scripts/installCore.sh
> Look for state systemIntegration instead of gitlab

- migrations/master.sql
https://github.com/Shippable/base/issues/1279
> add master integration and master integration fields for azure dc/os

- migrations/master.sql
https://github.com/Shippable/base/issues/1279
> changes name of azure-dc/os master integration

- migrations/master.sql
https://github.com/Shippable/base/issues/1274
> adds routeRoles for GET /passthrough/projects/:projectId/ymls

- scripts/bootstrapApp.sh
- scripts/provisionServices.sh
- https://github.com/Shippable/heap/issues/721
> fixing port mapping for local installation

- migrations/master.sql
https://github.com/Shippable/base/issues/1279
We will be adding this again after tomorrow's release.
> dropping azure dc/os migration

- usr/state.json.example
- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1286
> Add a new field hubspotRSyncLastSyncTime to systemConfigs

- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1288
> Stores pullRequestNumber in jobStatesMap for a pull request

- migrations/master.sql
- usr/system_configs.sql.template
> Add subscriptions.minionInstanceSize and systemConfigs.defaultMinionInstanceSize columns

- scripts/bootstrapApp.sh
- usr/state.json.example
- usr/system_configs.sql.template
> Populate systemConfigs.defaultMinionInstanceSize from systemSettings

- migrations/master.sql
https://github.com/Shippable/base/issues/1279
> adds azure dc/os masterintegrations and masterintegration field

- usr/system_configs.sql.template
https://github.com/Shippable/base/issues/1290
> add hubspotProjectsLastSyncTime to systemConfigs

- migrations/master.sql
fixes https://github.com/Shippable/base/issues/1301
> adds propertyBag and publicPipelineUser route role

- migrations/master.sql
> Open up GET /addons to justUser

- migrations/master.sql
Fixes https://github.com/Shippable/base/issues/1297
> Adds pullRequestRepoFullName column to runs

- migrations/master.sql
https://github.com/Shippable/base/issues/1303
> adding isPaid column to subscriptions table

- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1304
> populates subscriptions.isPaid column

- migrations/master.sql
https://github.com/Shippable/base/issues/1307
> Updates files to not create the sub.pipelineCount column

- migrations/master.sql
https://github.com/Shippable/base/issues/1311
> Allow public, publicPipeline access to artifact routes

- migrations/master.sql
> [merge after 5.5.3] Drop subscriptions.earlyAdopterMinionCount

- migrations/master.sql
https://github.com/Shippable/base/issues/1315
> add systemCodes for flag and job type viewObjects

- migrations/master.sql
https://github.com/Shippable/base/issues/1317
> adds migration for state resource

- migrations/master.sql
https://github.com/Shippable/base/issues/1319
https://github.com/Shippable/base/issues/1320
https://github.com/Shippable/base/issues/1321
Following json could be used for enabling the new master integrations.
```json
{
"type": "generic",
"name": "DOC"
},
{
"type": "generic",
"name": "GCL"
},
{
"type": "generic",
"name": "MAZ"
}
```
> Adds Google Cloud, MS Azure and Digital Ocean

- Dockerfile
> Use placeholder base image tag in Dockerfile

- migrations/master.sql
- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1329
> adds contextDetail column to jobStatesMap

- migrations/master.sql
https://github.com/Shippable/base/issues/1332
> adds status code for timeout for group status

- migrations/master.sql
- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1329
> update migrations to populate jobStatesMap

- migrations/master.sql
https://github.com/Shippable/base/issues/1334
> adds viewObjects and viewType for subscriptionDashboard

- migrations/master.sql
https://github.com/Shippable/base/issues/1336
> adds coloumn subscriptionId and updates index

- migrations/master.sql
https://github.com/Shippable/base/issues/1338
> adds migration to change type of operationResourceName in jobDependencies

- migrations/master.sql
https://github.com/Shippable/api/issues/17832
> Adds not null constraint on subscriptionIntegration.masterIntegrationId

- migrations/master.sql
https://github.com/Shippable/base/issues/1341
> changes view.displayName and viewObject.obejctId limit to 255

- migrations/master.sql
https://github.com/Shippable/base/issues/1341
> adds systemcodes for projectDashBoard and customDashboard

- migrations/master.sql
https://github.com/Shippable/base/issues/1346
> adds contextTypeCode releaseTag

- migrations/post_install/master-post_install.sql
https://github.com/Shippable/base/issues/1329
> populates jobStatesMap

- migrations/master.sql
https://github.com/Shippable/base/issues/1349
> adds projectId to views

- migrations/master.sql
https://github.com/Shippable/pm/issues/8461
> adds systemCode for showSPOGView
