Shippable/base

data/config.json.example

fixes https://github.com/Shippable/base/issues/170

Add emailServiceName to config example

---

data/config.json.example
data/state.json.example
scripts/bootstrapApp.sh
scripts/remote/migrations.sql
scripts/remote/systemConfigsData.sql.template
scripts/remote/system_configs.sql

#349 
Matches `hubspotEnabled` and `allowCustomNodes`.  The default is `0`, which represents never removing the console logs.

#349; adds consoleMaxLifespan.

---

data/config.json.example
data/state.json.example
scripts/bootstrapApp.sh
scripts/remote/migrations.sql
scripts/remote/systemConfigsData.sql.template
scripts/remote/system_configs.sql

#350 
The same as for `consoleMaxLifespan`, but in this case `0` is midnight.

#350; adds consoleCleanupHour.

---

versions/v4.10.28.json

#359 
Adds `coreServices` and the rest of the masterIntegrations to `integrationServices` and services to `serviceConfigs`.  IRC is only in coreServices because it has no integration, and NF only for IRC.  Other than NF, core services are not listed in integrationServices because they will run regardless of the integrations enabled.

#359; fills in integrationServices and serviceConfigs.

---

migrations/v4.10.31.sql

https://github.com/Shippable/base/issues/476
- Moves the deletion of the vault masterIntegrationFields before the deletion of the githubAuth masterIntegrationFields. This ensures that the correct masterIntegrationFields are deleted.
Tested by running the migration script locally; the githubAuth masterIntegrationFields were correctly deleted.

Move vault deletions before deletions from masterIntegrationFields

---

migrations/v4.11.3.sql

#488 
Adds defaults to `subscriptions.privateJobCount`, `transactions.discount`, and `transactions.price` if they're missing.  And updates the column types for `discount` and `price` if they're 'double precision' instead of 'numeric'.

#488; corrects column types and defaults.

---

migrations/v4.11.3.sql

https://github.com/Shippable/base/issues/493
- Doesn't create the accountId foreign key on transactions
- Removes the accountId foreign key from transactions
Tested by running the migration script. The foreign key was removed (and never created).

Remove accountId foreign key from transactions

---

migrations/v4.11.3.sql

https://github.com/Shippable/base/issues/507
- Adds serverEnabled if it doesn't exist (previously it was only added if braintreeEnabled didn't exist)
Tested by running the migration script locally.

Add serverEnabled if it doesn't exist

---

migrations/v4.11.3.sql

https://github.com/Shippable/base/issues/528
- Adds route permissions for `/accountIntegrations/:id/validateProjectOwnerToken`
- Deletes route permissions for `/accountIntegrations/:id/validateOwnerToken`
Tested by running the migration script. The db was updated and the correct route permissions were removed/added.

Rename validateOwnerToken to validateProjectOwnerToken

---

migrations/v4.11.3.sql

https://github.com/Shippable/base/issues/549
- Adds routePermissions for /projects/:id/owners
- Only accessible by project owners, not collaborators or members
tested by running the migration on the local db; the correct route permission was created.

Add routePermissions for /projects/:id/owners

---

migrations/v4.11.3.sql

https://github.com/Shippable/base/issues/549
- Removes routePermissions for `/projects/:id/owners`
- Adds routePermissions for `/projects/:projectId/owners`
tested by running the migration script; the correct routePermissions were added/removed, and the route works with postman.

Change /projects/:id/owners to /projects/:projectId/owners

---

migrations/v4.12.0.sql

#590 
Adds codes for the system-level roles.  Tested by running the migration script locally.

#590; add system-level role codes.

---

migrations/v4.12.0.sql

- https://github.com/Shippable/base/issues/589
- since there is no `member`, `collaborator` or `admin` access control on accounts, we dont need to add the permissions for those. the only permission that needs to be checked is whether the user has `justUser` role.

fixing route permissions for account routes

---

migrations/v4.12.0.sql

https://github.com/Shippable/api/issues/15664
- Changes the routePatterns for account routeRoles from :id to :accountId
Tested by running the migration script; the changes were reflected in the db.

Change routePatterns for account routeRoles from :id to :accountId

---

migrations/v4.12.0.sql

Shippable/api#15633
Tested by running the migration script and checking that the new route permissions were in the database.

Adds subscription routes to be updated.

---

scripts/getConfigs.sh

- https://github.com/Shippable/base/issues/603
- tested this by updating minor release versions locally

setting correct release version when upgrading

---

migrations/v4.12.0.sql

#601 and #602 
Adds routeRoles for `GET /projects`, `GET /projects/:projectId`, and `POST /projects/:projectId/disable`.  The roles in the database appear to be correct.

#601 and #602; adds routeRoles for projects routes to be updated.

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/616
according to the routing permissions table, POST /accountIntegrations needs the following entries
```
perform set_route_role(
routePattern := '/accountIntegrations',
httpVerb := 'POST',
roleCode := 6000
);
perform set_route_role(
routePattern := '/accountIntegrations',
httpVerb := 'POST',
roleCode := 6010
);
perform set_route_role(
routePattern := '/accountIntegrations',
httpVerb := 'POST',
roleCode := 6020
);
```
member, collaborator and admin permissions.
But, accountIntegrations POST is happening only in UI of loggedIn user. So, I have added only the permission for `justUser`. 
1) is the logic right ? Do we need only `justUser` permission ?
2) If not, what is the real use of having member, collaborator and admin roles ?

adds routeRoles for POST /accountIntegration

---

base.sh

Using tee to stream logs results in a 0 exit code always. Using PIPESTATUS, which is bash specific, will retain the exit code.
Fixes #633

Exit with the correct status code

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/637
- Adds justUser routeRoles for GET and POST /vortex
Tested by running the install from scratch; the routeRoles were created in the db.

Add routeRoles for vortex

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/652
Adds routeRoles for GET /subscriptions/:subscriptionId
Tested by running the installer from scratch; it succeeded, and the roles were created in the db.

Add routeRoles for GET /subscriptions/:subscriptionId

---

base.sh
scripts/bootstrapApp.sh
usr/state.json.example

There are a few changes here:
* If a release is being made, migrations run _before_ API boots up. This will allow any fields that the API needs to be added.
* If an install is being made, migrations runs _after_ API boots up, as the tables required for migrations are created by the API.
* API restarts following this to cache any new values.
Fixes https://github.com/Shippable/base/issues/658

Restart API following migration.

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/728
ran and tested the migrations in local and the new routeRoles were getting added for subscriptionIntegrationPermissions

adds routeRoles for subscriptionIntegrationPermissions

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/744
- Adds routeRoles for resources routes
Tested by running the installer from scratch. The installer was successful, and the routeRoles were created in the db.

Add routeRoles for resources

---

migrations/v4.12.1.sql

https://github.com/Shippable/base/issues/752
ran the migrations in local; the routeRoles were getting added in the db.

adds routeRoles for jobs

---

migrations/v4.12.1.sql

https://github.com/Shippable/api/issues/16223

uses the routeObject/:routeObjectId convention for the DELETE jobCoverageReports and subscriptionIntegrations/getDependencies routes

---

migrations/v4.12.1.sql

https://github.com/Shippable/api/issues/16243

updates migration to use :transactionId instead of :id in transaction routes

---

scripts/_manageServices.sh
scripts/bootstrapApp.sh
scripts/provisionServices.sh
usr/state.json.example
versions/v4.12.1.json

- https://github.com/Shippable/base/issues/780
- for a new installation, user will be prompted to set the replicas count. if the user wants to set default, then they'll set `installStatus.replicasConfigured=true` in state file
- for updating an existing installation, no action is required. all upgrades will use the configured replica count for services
- for updating from an older version of installer, state file needs `installStatus.replicasConfigured=true` flag to be set

using replica count from state file

---

migrations/v5.1.1.sql

#880 
Adds a systemCode for `provision` jobs.  Tested by running the installer and checking that the systemCode was in the database twice.

#880; adds systemCode for provision.

---

scripts/bootstrapApp.sh
versions/v5.1.1.json
versions/v5.1.2.json

#888 
Moves the new `provision` microservice from 5.1.1 to the new 5.1.2 and updates another new stepExec reference.  This also ran locally and resulted in a running `provision` container.

#888; moves provision from v5.1.1 to v5.1.2.

---

versions/v5.1.4.json
versions/v5.1.5.json

https://github.com/Shippable/base/issues/915
- Adds provision as a GKE integration service
Tested by upgrading a local installation to 5.1.4; the provision microservice was created and it connected to the queue.

Add provision as a GKE integration service

---

migrations/v5.1.5.sql

#926 
Tested by running the migration script a few times and checking that the `builderAccountId` was only set by the script on projects that did not already have a `builderAccountId` and then re-installing.  The migration is needed for installations with `autoSelectBuilderToken` false so that webhooks will function if already-enabled projects don't have a `builderAccountId` before upgrading.

#926; sets builderAccountId when ownerAccountId is available.

---

migrations/v5.2.1.sql

https://github.com/Shippable/base/issues/934
- Adds systemCodes for a new job (runCLI) and a new resource (cliConfig).
tested by running the migration script on an existing install, and by running the installer to update to a new release.

Add systemCodes for runCLI and cliConfig

---

migrations/v5.1.5.sql
migrations/v5.2.1.sql

Looked at all migrations following v4.12.3, everything except "accountRoles" should be okay. The script isn't idempotent as we skip something if its not available, but it should allow the installation to continue.
To test this I did the following:
* Made a release of v4.12.3(ran twice to allow migrations to run correctly)
* Made a release of v5.1.5. Saw the error:
```
'/home/shrivara/shippable/base/migrations/v5.1.5.sql' -> '/home/shrivara/shippable/base/scripts/local/data/migrations.sql'
psql:/tmp/data/migrations.sql:2510: ERROR:  relation "accountRoles" does not exist
LINE 1: SELECT not exists (select 1 from "accountRoles" where "accou...
^
QUERY:  SELECT not exists (select 1 from "accountRoles" where "accountId" = '540e55445e5bad6f98764522' and "roleCode" = 6100)
CONTEXT:  PL/pgSQL …
```

Ensure table exists before running migration

---

scripts/bootstrapApp.sh

Will patch the release once all the changes are in.
#948

Run migrations after API boots up everytime

---

migrations/v5.2.3.sql

Left over systemCodes from https://github.com/Shippable/pm/issues/7813 which need to be cleaned up, in order to prevent their creation in RC environment.

removes ciYmlIntegrationGroup from systemCodes

---

migrations/post_install/master-post_install.sql

removing the transaction(begin & end), because rollback is not required for these queries. With this, we will know which query is is currently running.

removing begin & end, not a transaction

---

scripts/bootstrapApp.sh

https://github.com/Shippable/pm/issues/7995
Sleep was added because WWW was failing due to above PM issue. Since, it is resolved, we can remove the sleep.

removing sleep between api stop & start

---

scripts/bootstrapApp.sh
usr/state.json.example

https://github.com/Shippable/base/issues/1133
- Removes nodeScriptsRemoteLocation from state.json
- Removes the copy_node_scripts function (and references); copying is now happening in api
- Fixes a couple typos in the `_map_env_vars` function in `bootstrapApp` (the typo wasn't affecting functionality, as it was reassigning the value of the same variable multiple times)
Tested by installing from scratch, as well as running an upgrade.

Remove copy_node_scripts; update value for nodeScriptsLocation

---

usr/state.json.example
versions/master.json

https://github.com/Shippable/base/issues/1134
- Removes ini queue and other unused queues
- Removes ini from the installed services list
Tested by doing a fresh install and an upgrade.

Remove ini from installer; delete unused queues

---

migrations/master.sql

https://github.com/Shippable/base/issues/1142
- Removes ADD COLUMNS and ALTER COLUMNS for columns that are later dropped
Tested by upgrading an existing install, and by doing a fresh installation

Remove 'add columns' for dropped columns

---

migrations/master.sql

Fixes https://github.com/Shippable/base/issues/1151
This took `6.495 ms` for `256` subs on rc.

Adds index on providerId + orgName in subscriptions

---

migrations/master.sql
migrations/v5.3.2.sql

https://github.com/Shippable/base/issues/1170
- No longer tries to create the subProviderIdOrgNameI index concurrently
Tested by upgrading to v.5.2.3 and master, as well as doing a fresh local install with master. The index was created and the migrations ran with no errors each time.

Do not create the subProviderIdOrgNameI index concurrently

---

migrations/master.sql

#1309 
Adds the new fields to systemSettings if there is a systemSettings table.  Tested upgrade with and without systemSettings.

#1309; adds new hubspot fields to systemSettings.

---

migrations/master.sql

https://github.com/Shippable/base/issues/1327
We have ~6k subInts in prod, so it should not take up a lot of time to run the migration.

Adds masterIntegrationId column to subcriptionIntegrations
